export const CREATE_BODIES = 'CREATE_BODIES';
export const CREATE_DIVISIONS = 'CREATE_DIVISIONS';
export const CREATE_DIVISION_LEVELS = 'CREATE_DIVISION_LEVELS';
export const CREATE_OFFICES = 'CREATE_OFFICES';
export const CREATE_OFFICEHOLDERS = 'CREATE_OFFICEHOLDERS';
export const CREATE_PARTIES = 'CREATE_PARTIES';
export const CREATE_PEOPLE = 'CREATE_PEOPLE';
