# Generated by Django 2.1.5 on 2019-01-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='uid',
        ),
    ]
