# Generated by Django 2.1.5 on 2019-01-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0002_remove_party_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='race',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state_of_residence',
        ),
        migrations.RemoveField(
            model_name='person',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated',
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullstack.Party'),
        ),
    ]
