# Generated by Django 2.1.5 on 2019-01-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0004_officeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='party',
        ),
        migrations.AddField(
            model_name='officeholder',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullstack.Party'),
        ),
    ]
